invertase/react-native-google-mobile-ads

- lib/AdsConsent.js
- lib/internal/GoogleAdsNativeEventEmitter.js
This fixes #9 and makes the package usable again. With this changes I was able to render a banner ad again.
> fix: incorrect module naming

- docs/european-user-consent.mdx
- docs/index.mdx
- lib/ads/BannerAd.js
I just initialized a new RN project, followed the docs and noticed the app would crash at first.
The crash was because the google ads sdk couldn't find the app_id from the app.json config.
Therefore I updated the docs.
Then I noticed banners would still not render, one more name change was required (which I think I forgot to push in my previous PR's).
> fix: displaying banner ads, wrong config in docs

- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
Banners were not working because of a naming mismatch.
> fix: banner ads not working on android

- android/src/main/java/io/invertase/googleads/ReactNativeAppModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsConsentModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsPackage.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsRewardedModule.java
- android/src/main/java/io/invertase/googleads/common/RCTConvert.java
- android/src/main/java/io/invertase/googleads/common/ReactNativeEventEmitter.java
- android/src/main/java/io/invertase/googleads/common/ReactNativeModule.java
- ios/RNGoogleAds/common/RNRCTEventEmitter.m
- lib/index.js
- lib/internal/GoogleAdsNativeEventEmitter.js
- lib/internal/registry/nativeModule.js
> fix: interstitials and rewarded ads

- package.json
Currently the google-ads config in app.json is ignored because the path to react-native.config.js is incorrect.
> fix: incorrect rn config path

- docs/index.mdx
Currently the docs make it seem like setting setRequestConfiguration is mandatory.
Actually it's only needed if your app requires specific targeting or you need to provide testID's.
> docs: improve outbound requests info

- __tests__/googleAds.test.ts
- e2e/interstitial.e2e.js
- e2e/rewarded.e2e.js
- ios/RNGoogleAds/RNGoogleAdsModule.m
- ios/RNGoogleAds/RNGoogleAdsRewardedModule.m
- lib/ads/InterstitialAd.js
- lib/ads/RewardedAd.js
- lib/index.d.ts
- lib/index.js
- lib/validateAdRequestConfiguration.js
Fixes #3, Fixes #5
Also makes sure that the default export aligns with the docs and previous rnfb implementation. (Calling admob().setConfiguration() instead of admob.setConfiguration())
> fix: rewarded ads crash & request configuration

- android/build.gradle
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsCommon.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsEvent.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsRewardedModule.java
- example/android/build.gradle
- ios/RNGoogleAds/RNGoogleAdsCommon.h
- ios/RNGoogleAds/RNGoogleAdsCommon.m
- lib/AdEventType.js
- lib/index.d.ts
- type-test.ts
Android Update Banner, Interstitial, Rewarded add to be compatible with com.google.android.gms:play-services-ads:20.5.0
BREAKING CHANGES:
Please refer to upstream guides for suggestions on new usage. https://developers.google.com/admob/ios/migration and https://developers.google.com/admob/android/migration
- compileSdkVersion now 31, change your app android build.gradle to 31 if you have not already. Note that JDK11 is required for stable compilation on compileSdkVersion 31, JDK8 has internal compiler errors with SDK31
- onAdLeftApplication removed from the underlying SDK, use react-native built in AppState to determine app went to background
- Smart banner ads removed; use adaptive banner ads. Set height/width explicitly taking into account device size
> feat(android, sdks)!: update to the latest gms:play-services-ads:20.5.0

- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java
- docs/index.mdx
- ios/RNGoogleAds/RNGoogleAdsModule.m
- lib/googleMobileAds.js
- lib/index.d.ts
It has been adviced to initialize the sdk before loading ads. (Especially when using mediation).
Therefore these methods should be exposed to RN.
Solves: #4
> feat: expose native SDK initialize methods as new `initialize` API

- .github/PULL_REQUEST_TEMPLATE.md
- android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
Fixes initial loads of `<BannerAd>`. See #58 for details.
Fixes #58 
- I read the [Contributor Guide](https://github.com/invertase/react-native-google-ads/blob/main/CONTRIBUTING.md)
---
Think `react-native-admob` is great? Please consider supporting the project with any of the below:
> fix: no banner ads loaded on Android in the first render

- src/common/serialize.ts
- src/common/validate.ts
- src/internal/registry/nativeModule.ts
- src/validateAdRequestOptions.ts
- src/validateAdShowOptions.ts
Currently some type validation helpers from common weren't used as those resulted in TS errors.
By defining a "Type predicate", TS understands the validation functions.
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
> refactor: use type predicates

- docs/index.mdx
Removed erroneous semi-colon in code snippet
Fixed syntax error in documentation 
N/A
N/A
- I read the [Contributor Guide](https://github.com/invertase/react-native-google-ads/blob/main/CONTRIBUTING.md)
- [ X] Yes
N/A
> docs(docs): fixed syntax error

- .github/workflows/create_test_patches.yml
with the previous scoped package name we needed to pushd to `@invertase`, that is unnecessary and causes an error now
Nothing logged, but I watch CI and saw failures...
It is a conventional commit so it *should* be okay to rebase merge. Always verify that assertion though :-)
Not sure if this is testable pre-merge, it *may* run correctly on the branch for the PR. If not it may need merging, then we will see if the patch-packages zip is created successfully
---
Think `react-native-google-mobile-ads` is great? …
> build(patches): remove reference to previous scoped package dir

- example/App.tsx
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- example/package.json
- example/yarn.lock
Add a test case for the AdConsent interface to `App.tsx`.
The test case does not work with the default AdMob App IDs.
The UMP has to be configured in the AdMob/Ad Manager backend for the test case to work.
Closes #64 
---
> test(example): add AdConsent test

- docs/index.mdx
This npx command is convenient method for installing packages and doesnt need to going in and out ./ios folder
🔥
> docs(ios): Replace pod install with npx pod-install

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsModule.java
> fix: mediation adapter failed to init

- docs.json
- docs/displaying-ads-hook.mdx
- example/App.tsx
- example/ios/Podfile.lock
- example/yarn.lock
- package.json
- src/hooks/useAppOpenAd.ts
- src/hooks/useFullScreenAd.ts
- src/hooks/useInterstitialAd.ts
- src/hooks/useRewardedAd.ts
- src/index.ts
- src/types/AdStates.ts
- yarn.lock
This PR add supports for hook-style ad state management which can be used for full screen ads(AppOpen, Interstitial, Rewarded). This feature is initially implemented in another admob library, [@react-native-admob/admob](https://github.com/react-native-admob/admob).
I'm happy to join forces on this single package which can be maintained better😁.
add full screen ad hooks
---
- 👉 Star this repo on GitHub …
> feat: add full screen ad hooks

- .eslintrc.js
- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- docs/common-reasons-for-ads-not-showing.mdx
- docs/displaying-ads.mdx
- docs/european-user-consent.mdx
- docs/index.mdx
- docs/migrating-to-v5.mdx
- e2e/consent.e2e.js
- example/App.tsx
- example/yarn.lock
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- package.json
- src/AdsConsent.ts
- src/AdsConsentPurposes.ts
- src/AdsConsentSpecialFeatures.ts
- src/index.ts
- src/types/AdsConsent.interface.ts
- yarn.lock
v5.0.0 introduced the UMP SDK, which stores the consent as an encoded string on the device and doesn't provide further information. It is a common use case to act upon a user's choices though, especially as the Google Mobile Ads SDK won't serve any ads if the user doesn't at least provide consent to store and/or access information on the device. This PR aims to bridge that gap by introducing a new method to the `AdsConsent` interface called `getUserChoices` (happy to hear other suggestions).
I also went ahead and replaced the JSDocs inside `src/AdsConsent.ts` with TypeScript types. If the JSDocs serve a purpose, then let me know and I'll revert.
Related to https://github.com/invertase/react-native-google-mobile-ads/issues/96
- My change …
> feat(consent): add method that returns consent choices

- RNGoogleMobileAds.podspec
AppTrackingTransparency framework only exists on iOS14+ so if we ask cocoapods to link the framework we get a crash during the link phase on ios14
Switch to "weak_frameworks" for the framework reference, and app appears to boot fine now
Thanks to @ccorneliusHsv for taking the time to report it!
Fixes #111 
commit is conventional, semantic release should work
You need an iOS13 simulator to reproduce the crash, it crashes on v5.0.0 and v5.1.0
After this change and a `pod install` the example app works on the same …
> fix(ios): avoid crash on ios < 14 without AppTrackingTransparency

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsAppOpenModule.java
- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsInterstitialModule.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.m
- ios/RNGoogleMobileAds/RNGoogleMobileAdsInterstitialModule.m
- src/ads/AppOpenAd.ts
- src/ads/InterstitialAd.ts
- src/ads/MobileAd.ts
- src/ads/RewardedAd.ts
- src/types/GoogleMobileAdsNativeModule.ts
Moved common `load` and `show` methods in each full screen ad classes into `MobileAd` class.
---
> refactor: move common ad logics to mobilead class

- src/index.ts
- src/types/index.ts
Added internal types to export list in index.ts.
Library users will be able to use library more flexibly with the exported types.
export types
---
> refactor: export types to index

- src/types/GoogleMobileAdsNativeModule.ts
- src/types/MobileAdsModule.interface.ts
Fixes wrong return type of `openAdInspector` method in `MobileAds` class.
fix wrong openAdInspector method return type
---
> fix(types): openAdInspector returns Promise, not function

- package.json
- yarn.lock
Upstream fixed binary issue, see https://github.com/angular/clang-format/issues/78
No release needed, all are devDependencies 
checked clang-format specifically - it works fine, CI will probe the rest
---
> build(deps): `yarn package:update` to ingest clang-format@current

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerViewManager.m
Before this change, Banner Ad requested ad multiple times when props are set because we requested ad on every prop changes.
This change batches the prop changes and makes it to request ad only once.
Batch banner ad props update
---
> fix: batch banner ad prop update

- ios_config.sh
So on March 24 macOS 12.3 was released, and in that release they removed `/usr/bin/python` (the `python` that you will pick up in Xcode builds)
Our iOS config script that takes the app.json and puts it into your Info.plist so it is then available programmatically in javascript relied on `python` and silently failed when `python` wasn't there
So this adds a check for the new python3 that we are using, and forward ports our python chunk in the build script to python3 style
It's been tested and released and received success reports in the wild, so I'm comfortable with the code and it definitely needs a fix+release here
Related https://github.com/invertase/react-native-firebase/pull/6234
It's a conventional commit, it'll trigger the right release
- I read the [Contributor …
> fix(ios): use python3, fixes issues on macOS 12.3+

- src/ads/MobileAd.ts
Rewarded interstitial ads seem to throw an error when creating an event listener, even though the event type is valid.
Fixes #147
The expected event type is `rewarded_interstitial`, although error checking 
Before:
After:
---
> fix(rewarded interstitial, ios): fixed false error with valid event type value

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsModule.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.m
If ad inspector got error while opening, the following error occured:
`No callback found with cbID # and callID # for RNGoogleMobileAdsModule.openAdInspector - most likely the callback was already invoked.`
This was because we are resolving the promise even the promise is rejected already.
Fix ad inspector callback error
---
- 👉 Follow …
> fix: fix ad inspector callback error

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsCommon.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m
- src/types/RequestOptions.ts
- src/validateAdRequestOptions.ts
This PR adds `publisherProvidedId` property to RequestOptions.
Related link: https://developers.google.com/ad-manager/mobile-ads-sdk/android/targeting#publisher_provided_identifiers
Added `publisherProvidedId` property to request options
---
> feat: add ppid option to request options

- docs/european-user-consent.mdx
- docs/index.mdx
it was possible before but never documented, it's important now that react-native-firebase v15+ requires `use_frameworks!`
Related #173
A single conventional commit
I ran `yarn lint:markdown:check` (also `yarn lint:markdown:fix` which altered a couple other things...)
---
> docs(ios, frameworks): document how to set up static frameworks

- package.json
Update to new minor version of iOS SDK
May fix #173 - needs testing :eyes: @RodolfoGS
Should be released at same time as bump to android SDK which is a breaking change as minSdkVersion goes to 19 there:
Why combine in one breaking release? This change has this:
> Updated minimum supported Xcode version to 13.2.1.
Which is a tiny break, but still a break. Do them at same time I think
---
- 👉 Star this …
> feat(ios, sdk)!: use google-mobile-ads-sdk 9.6.0 requires Xcode >= 13.2.1

- RNGoogleMobileAdsExample/app.json
- android/build.gradle
- android/src/main/AndroidManifest.xml
- package.json
Update to the new underlying SDK. This had no code breaking changes but does bump the minSdkVersion, so for that it is a breaking change
I also implemented the new background-thread optimization feature for android via app.json toggles to fill in the AndroidManifest.xml items
Fixes #175
Unblocks #174 
conventional commits including breaking change notice
Ran all the tests locally, examined lint output and grepped codebase for deprecated items from the upstream migration doc, all clean
---
Think …
> feat(android, sdk)!: android ads sdk v21, requires android minSdkVersion 19+

- android/build.gradle
@birdofpreyru noticed and helpfully pointed out that our kotlin plugin build dependency wasn't correct, and I think this corrects it 
Fixes #180 
Single conventional commit
CI should handle but hopefully @birdofpreyru can also try the patch-package set to verify since he's got this reproducing locally :pray: 
---
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) …
> fix(android, build): correct kotlin plugin dependency

- docs/displaying-ads-hook.mdx
- src/hooks/useFullScreenAd.ts
I find it weird that `isLoaded` in hooks doesn't change value when ad is shown. In fact, the value `isLoaded = true` after ad has been shown is wrong since a new ad has not been loaded and calling `show` will fail.
- ~~My change includes tests;~~
I wanted to add some tests on `useRewardedAd` hook but I had this error
```bash
TypeError: RNAppModule.eventsNotifyReady is not a function
34 |   ) {
35 |     if (!this.ready) {
> 36 |       RNAppModule.eventsNotifyReady(true);
|                   ^
37 |       this.ready = true;
38 |     }
39 | …
```
> feat(hooks)!: automatically set isLoaded to false

- RNGoogleMobileAdsExample/ios/Podfile.lock
- package.json
I saw there were new SDKs, so I bumped them to current
None logged
conventional commit
Tested locally, no regressions detected, hopefully low risk / just works...
---
> fix(deps): android sdk 21.1.0 / ios sdk 9.9.0

- docs/displaying-ads-hook.mdx
In ios device (development build with eas), doesnt load ad with "Interstitial" but has loaded "INTERSTITIAL"
---
> docs: correct spelling of CHANGELOG

- RNGoogleMobileAdsExample/ios/Podfile.lock
- RNGoogleMobileAdsExample/package.json
- RNGoogleMobileAdsExample/patches/@react-native-community+cli-platform-ios+7.0.1.patch
- RNGoogleMobileAdsExample/yarn.lock
- package.json
Just native SDK bumps along with some minor test stuff I needed in order to get them to run in my environment
Nothing controversial here and it passes my testing locally
Was "in the area..." of mobile ads because a user was reporting a crash and I wanted to validate it was still working. It's working...
conventional commits
I ran the example app locally and verified everything I could verify, appears to work fine
---
Think `react-native-google-mobile-ads` is great? Please consider supporting the project with …
> feat(deps): native admob SDK bumps - iOS 9.10.0 / android 21.2.0

- ios_config.sh
The error message had a typo, which is not a great developer experience...
Noted in #219
conventional commit
None, visual inspection should be sufficient
---
> fix(ios, config): fix typo in ios_app_id error message

- RNGoogleMobileAdsExample/App.tsx
- RNGoogleMobileAdsExample/android/app/build.gradle
- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsAdHelper.kt
- refresh-example.sh
The android ad helper object was using reflection to access a bunch of admob SDK methods, which means that proguard is not able to determine the classes were needed so it was either obfuscating the names (so they weren't found) or stripping the classes (so they were not found)
Either way, it is much simpler to just refactor the code to use concrete APIs vs reflection, then no proguard tricks are required
Related: our test app did not have much support for android release mode testing so I added a bunch of stuff there
Fixes #183 
Fixes #241 
Related #161 (load events not coming through in release mode?)
conventional commits
and followed the process outlined there for …
> fix(android, release): fix proguard-related crashes in android release mode

- docs/index.mdx
This PR adds docs about how expo users can enable static frameworks. We already have docs for non-expo users but they require extra knowledge to be useful for expo users to lazy to google it.
- Related to #176
- Related to #173
Proofread what I wrote. I linked related docs. Setup is the same as in rnfirebase.
:fire: :)
---
- 👉 Follow …
> docs(ios,expo): how to enable static frameworks

- __tests__/interstitial.test.ts
- jest.setup.ts
- src/ads/MobileAd.ts
If an ad fails to load its `_isLoadCalled` flag would still remain true causing further `load()` calls to do nothing. This prevented me from reloading interstitial and rewarded ads after they initally failed to load (eg. due to no-fill or network errors). This PR resets the `_isLoadCalled` flag if an ad failed to load with an error.
- Fixes #195
Allow load to be called again after an ad failed to load.
Ran these changes in production using patch-package for a while. Also added unit tests, they pass.
:fire: ;) …
> feat: allow load to be called again after error

- docs/european-user-consent.mdx
Add guide for Expo user when config Android proguard-rules
---
> docs(consent, android): added guide for Expo users

- ios_config.sh
Tweak the ios_config.sh error to mention the `GADApplicationIdentifier` key from the Info.plist using the correct value - it may help with Ctrl-C troubleshooting.
> fix(ios): correct typo in ios_config.sh

- ios_config.sh
This removes any possible ambiguity on what utility we require for config, solving a problem where sometimes a utility that performs HTTP HEAD requests is found instead of the standard BSD file utility
Fixes #279 
Related https://github.com/invertase/react-native-firebase/pull/5805 / https://github.com/invertase/react-native-firebase/issues/5801
Tested by original reporter, in successful use for approximately a year in react-native-firebase
---
Think `react-native-google-mobile-ads` is great? Please consider …
> fix(ios): use fully-specified path to required head utility

- ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m
Currently adaptive banner ads can overlap with the notch / dynamic island in landscape mode.
They should take safe areas into account.
Source:
https://developers.google.com/admob/ios/banner/anchored-adaptive#implementation_notes
> fix(ios): adaptive banner should take safe areas into account

- src/types/AdapterStatus.ts
As described in the documentation, this will be under the initialization process.
```ts
mport mobileAds from 'react-native-google-mobile-ads';
mobileAds()
.initialize()
.then(adapterStatuses => {
// Initialization complete!
});
```
The actual values returned during initialization can be seen in the console as follows.
```zsh
{"adapterStatuses":
[
{
"description": "<GADAdapterStatus: 0x283ad8ec0;state = Ready>",
"name": "GADMobileAds",
"state": 1
}
]
}
```
Think `react-native-google-mobile-ads` is great? Please …
> fix(type): fixed  mobileAds initialize response status type

- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerViewManager.m
I was not able to receive any AppEvent fired from the ads on iOS while it worked fine on Android.
After some digging, it turns out that `RNGoogleMobileAdsBannerViewManager` used an incorrect method signature:
https://developers.google.com/admob/ios/api/reference/Protocols/GADAppEventDelegate
it should be `[-adView:didReceiveAppEvent:withInfo:]` intead of `[-bannerView:didReceiveAppEvent:withInfo:]`
N/A
- Fix not being able to receive banner app event on iOS
Verified on iOS 16 that the native code is now able to …
> fix(banner, ios): Fix not able to receive banner app event on iOS

- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.h
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.m
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerViewManager.m
Currently the BannerViewManager describes the classes BannerViewManager and BannerComponent. They should be separated for clarity and this makes for e.g. migrating to the new architecture easier.
> refactor(ios): move banner component class into dedicated file

- docs/european-user-consent.mdx
- docs/index.mdx
All iOS apps should request the app tracking transparency, so make this part of the installation flow.
> docs(ios): add advice on requesting app tracking transparency

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsAppOpenModule.kt
- package.json
Breaking changes:
- Ads are no longer served on iOS 11. iOS 12 is required to retrieve ads, though iOS 10 is still supported.
- Building with bitcode is no longer supported. Disabling bitcode in your mobile apps is now required to integrate the Google Mobile Ads SDK.
- Deprecated [AppOpenAd.load()](https://developers.google.com/android/reference/com/google/android/gms/ads/appopen/AppOpenAd#load(android.content.Context,%20java.lang.String,%20com.google.android.gms.ads.AdRequest,%20int,%20com.google.android.gms.ads.appopen.AppOpenAd.AppOpenAdLoadCallback)) methods that accept an orientation input parameter and added new methods that don't take an orientation input. The new methods determine the orientation at request time, matching the behavior of other full-screen formats.
- Added …
> feat(deps)!: mobile ads sdk upgrade - ios 10.2.0 / android 21.5.0

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
- android/src/main/java/io/invertase/googlemobileads/common/ReactNativeAdView.java
unable to open the Ad Debug Menu via gesture on Android. This PR fixes that
Fixes #188 
Current release (10.0.0) unable to use two finger long press gesture to access debug menu on Android
With this PR, using the gesture activates the menu correctly.
iOS unaffected.
---
🔥
> fix(android banner): debug menu opening

- RNGoogleMobileAdsExample/App.tsx
- __tests__/googleMobileAds.test.ts
- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsModule.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.m
- src/MobileAds.ts
- src/types/GoogleMobileAdsNativeModule.ts
- src/types/MobileAdsModule.interface.ts
Opening the debug menu for ads via gesture works, however if the ad is not rendering, we have no way to trigger the gesture. this PR adds the functionality to programmatically open the debug menu (eg: via a button press).
Run the example app and open the Debug Menu test screen. Press the button, it should show the Debug Menu.
---
🔥
> feat(ads-module): open debug menu programmatically

- src/ads/GAMBannerAd.tsx
fix: for method ```recordManualImpression```  in ReactNativeGoogleMobileAdsBannerAdViewManager.java  
The Android Java code in ReactNativeGoogleMobileAdsBannerAdViewManager.java is expecting an Integer after ```Integer.parseInt``` but currently string 'recordManualImpression' is passed. 
---
> fix:  Solved issue with method recordManualImpression for GAMBannerAd

- package.json
BREAKING CHANGE:
- Updated minimum supported Xcode version to 14.1.
- armv7 is not supported in Xcode 14 and has been removed from the SDK.
- The minimum deployment target has been increased to iOS 11.0.
> feat(deps)!: mobile ads sdk upgrade - ios 10.5.0 / android 22.1.0

- android/build.gradle
```
Build file 'project_name/node_modules/react-native-google-mobile-ads/android/build.gradle' line: 120
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Cannot set the value of read-only property 'force' for DefaultExternalModuleDependency{group='com.google.android.gms', name='play-services-ads', version='22.1.0', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
```
> fix(android): fixed android build error issue for RN 0.72

- RNGoogleMobileAds.podspec
iOS build fails on RN v0.70.x
Fixed iOS builds to work on both architectures.
> fix(ios): Build support on both architectures

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
Consecutive calls to `getCurrentActivity` are not guaranteed to return the same result. Call to `getCurrentActivity` after our `null`-checks are thus part of a race condition. Calling `getCurrentActivity` only once solves this issue.
I verified the changes using the test app
---
> fix(android): race conditions getting current activity

- android/build.gradle
When I wanted to build the Android package in Windows environment, I was getting an error if there was no kotlinVersion parameter in my main project. Even if there was no kotlinVersion in my main project, it was using the version 1.6.0 written in these lines. This version causes an error when building.
So I upgraded to the latest version 1.8.22 that I could run.
Fixes https://github.com/invertase/react-native-google-mobile-ads/issues/405
> fix(android): kotlinVersion

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
UMP SDK version 2.1.0 exposes a few new methods and values which are not fully accessible though our wrapper yet. This PR proposes the following changes:
1. The existing `showForm` method currently only returns the updated value of the `getConsentStatus` method. However, calling `showForm` also updates the return value of `canRequestAds` (this is new in version 2.1.0), so I propose we let `showForm` return the updated result of `canRequestAds` as well.
2. The recently added `showPrivacyOptionsForm` method is essentially the same as the `showForm` method. It also updates the return values of `getConsentStatus` and `canRequestAds`. So I propose calling it should return exactly the same result type as the `showForm` method.
3. The upstream SDK unfortunately does not clearify whether showing …
> feat: return consent info whenever it changes

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- docs/european-user-consent.mdx
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
Version 2.1.0 of the UMP SDK added a new `loadAndShowConsentFormIfRequired` method. This PR exposes this method and recommends it in our docs over the old approach.
With this new method consent can be obtained like this:
```ts
import { AdsConsent, AdsConsentStatus } from 'react-native-google-mobile-ads';
const consentInfo = await AdsConsent.requestInfoUpdate();
const { status } = await AdsConsent.loadAndShowConsentFormIfRequired();
```
This release features a new `loadAndShowConsentFormIfRequired` method which simplifies obtaining consent from users.
- My change …
> feat(consent): expose the new loadAndShowConsentFormIfRequired method

- src/ads/MobileAd.ts
I tried to call addAdEventListener on a GAMInterstitialAd for events of type GAMAdEventType.APP_EVENT. However, an error was thrown:
"GAMInterstitialAd.addAdEventListener(*) 'type' expected a valid event type value."
After checking the source code, the issue is in the implementation of `_addAdEventListener`: the filter is missing the type GAMAdEventType.
Fixes #444 
Fix: missing events of type GAMAdEventType in addAdEventListener
- [ x ] Yes
- [ x ] `Android`
- [ x ] `iOS`
- [ x ] No
> fix: missing events of type GAMAdEventType in addAdEventListener

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
The just merged #436 introduces a race condition like the ones fixed in #418.
This change is simple enough to verify by review and green CI.
---
> fix(android): race condition getting current activity

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- docs/european-user-consent.mdx
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
As a latency best practice, Google recommends not waiting for the loadAndPresentIfRequired callback to complete so you can start loading ads as soon as possible after your app launches.
This PR adds a method that directly exposes the UMP Consent Information without having to wait for callbacks.
And so the SDK can be initialized faster if consent was obtained in a previous session.
See:
https://developers.google.com/admob/ios/privacy#request-ads
https://developers.google.com/admob/android/privacy#request-ads
> feat: initialize sdk in parallel

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.m
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerView.mm
Added methods to clean up the banner when a bannerView unmounts.
Might fix #496?
Please test.
> fix: banners not properly destroyed

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- docs/european-user-consent.mdx
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
This feature makes it possible to only show the ATT alert if consent (for Purpose 1) was given.
As advised by: https://developers.google.com/admob/ios/privacy/gdpr#frequently_asked_questions
See also: https://developers.google.com/admob/ios/privacy/gdpr#how_to_read_consent_choices
> feat: add method to check if consent for purpose 1 was given

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
A little refactoring of the banner initialization code for Android, motivated by [AdMob docs for mediation](https://developers.google.com/admob/android/mediation#initialize_your_ad_object_with_an_activity_instance).
Fixes #506 
Potentially improves mediation performance for banners on Android.
I ran the example app after update, it works fine. The change is also quite trivial.
---
- 👉 Star this repo on …
> feat(android): potentially improves mediation performance for banners

- src/AdsConsent.ts
This PR fixes the wrong value returned by AdsConsent.getUserChoices() for the createAPersonalisedContentProfile variable.
The createAPersonalisedContentProfile is compared to AdsConsentPurposes.CREATE_A_PERSONALISED_ADS_PROFILE while it should be compared to AdsConsentPurposes.CREATE_A_PERSONALISED_CONTENT_PROFILE.
---
- 👉 Follow …
> fix(consent): wrong value of user's consent to 'Create a personalized content profile' purpose

- RNGoogleMobileAds.podspec
- package.json
BREAKING CHANGES:
- The SDK no longer depends directly on GoogleAppMeasurement. To continue collecting user metrics in AdMob, link your AdMob app to Firebase and integrate the Google Analytics for Firebase SDK into your app.
- Updated the minimum supported Xcode version to 15.1.
- Increased iOS minimum deployment target to 12.0.
- Updated the minimum OS required to receive ads to iOS 13.
> feat(deps)!: mobile ads sdk upgrade - ios 11.0.1, ump sdk 2.2.0

- ios_config.sh
This wastes developer's time, we should warn them
Related:
- #547 - developer confusion
docs only, no release
No tests needed, all comments
---
> docs(ios): note that pod install is required to see ios_config.sh changes

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsFullScreenAdModule.kt
I was unable to build this and nobody else wanted to make a PR in the issue. I hope this resolves that issue. But the change has worked for me.
This PR fixes the android build issue: ReactNativeGoogleMobileAdsFullScreenAdModule.kt 'onAdLoaded' overrides nothing
#511 
---
> fix(android): forward port onAdLoaded signature for Kotlin 1.9

- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.m
https://github.com/invertase/react-native-google-mobile-ads/issues/496
- Fixes memory leak when using banners on iOS with old RN architecture.
---
> fix(banner, ios): fixed memory leak

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsCommon.java
- src/types/RequestOptions.ts
`AdManagerAdRequest.Builder().addCustomTargeting` supports passing both strings and ArrayLists. iOS already handles this.
- Add support for string[] in `customTargeting`
iOS ad loaded with strings and string[] in customTargeting:
Android
> feat(android): Add support for ArrayList

- docs/displaying-ads.mdx
The code provided by the docs creates a TypeScript error: "Argument of type 'string' is not assignable to parameter of type 'SetStateAction<number>'.ts(2345)." By initially setting the state to a string, the error is fixed.
> fix: Typescript error in the docs

- android/src/main/java/io/invertase/googlemobileads/OnNativeEvent.kt
When I added a Banner ad to the screen with Bridgeless and Fabric enabled, I got an error like below.
```
Error: Unsupported top level event type "topNative" dispatched
```
In _node_modules/react-native/.../ReactFabric-dev.js_ file, when I got to the relevant place, I saw that there is no "**topNative**".
I saw that there is "**topNativeEvent**" similar to this.
---
> fix: Unsupported top level event type "topNative" dispatched

- android/build.gradle
- app.plugin.js
- docs/european-user-consent.mdx
- docs/index.mdx
- ios_config.sh
- jest.config.js
- package.json
- plugin/__tests__/__snapshots__/plugin.test.ts.snap
- plugin/__tests__/fixtures/app-without-params.json
- plugin/__tests__/fixtures/app.json
- plugin/__tests__/fixtures/package.json
- plugin/__tests__/plugin.test.ts
- plugin/jest.config.js
- plugin/src/index.ts
- plugin/tsconfig.json
- src/types/BannerAdProps.ts
- yarn.lock
This PR adds an Expo config plugin. When Expo is used, the config plugin replaces the custom `app.json`/`ios_config.sh`/`build.gradle` configuration workflow. The docs have been updated accordingly. Note that if Expo is not detected, the "old" configuration workflow is used.
Here are some things to look out for while reviewing this:
On iOS the `ios_config.sh` file simply checks whether `expo` is one of the dependencies in the `package.json` file. IMHO that's sufficient because config plugins can be used anyways as soon as the `expo` package is installed.
On Android the `build.gradle` file checks whether the app native code depends on the native `:expo` project. In case you're wondering: yes, we could use the approach used for iOS here as well. The current approach was inspired by the …
> feat!: Add expo config plugin

- android/app-json.gradle
- android/build.gradle
- ios_config.sh
This PR removes the redundant and deprecated handling of `app.config.js` files from the `ios_config.sh` and `build.gradle` scripts.
Now that `app.config.js` support is handled by the Expo config plugin, the `ios_config.sh` and `build.gradle` scripts no longer need to consider `app.config.js` at all. Parts of the code added in #517 can be removed again to make the scripts easier to maintain. That's exactly what this PR does. It's simply reverting all changes to the relevant files from said PR. I double checked that this does only revert the `app.config.js` support and nothing else (e.g. fixes or other refactorings).
and followed the process outlined there for submitting …
> chore: remove redundant app.config.js support

- docs/common-reasons-for-ads-not-showing.mdx
During the setup and initialization of a new React Native project, especially when using npx react-native init ProjectName, the autogenerated package name may not always be unique or suitable for production environments or even for developing. This can lead to issues, particularly when integrating with services like Google AdMob, where a unique package name is mandatory to avoid conflicts and operational issues.
This can lead to issues where the request was succesfull but no ads even test ads will be delivered.
#607 
- This is a breaking …
> docs(ads-not-showing): Added info section about applicationId related issues to "Common reasons for ads not showing" 

- docs.json
- docs/ad-inspector.mdx
- docs/european-user-consent.mdx
- docs/index.mdx
I spend some time putting Bare RN and Expo specific parts of the documentation in side-by-side tabs. Looks like this:
This is a docs.page feature which I quite like. I made sure all tabs are synchronized, meaning if you choose Expo for example, all tabs will switch to Expo. Default is React Native.
I also fixed the mess at the beginning of the startpage. It always confused me that we had the following sections in that order: Installation; Optional static frameworks; What does the package do; Actual Installation Instructions.
Instead, the "What does the package do" is now first and then followed by all installation instructions. Note that for Expo I recommended `npx expo install react-native-google-mobile-ads`. This does not only install the dependency, but also adds the expo config plugin …
> docs: add framework tabs and nav sections

- docs/displaying-ads-hook.mdx
- docs/displaying-ads.mdx
- docs/european-user-consent.mdx
- docs/index.mdx
This PR replaces some blockquotes in the docs with docs.page callout components.
We often use blockquotes in the docs to give users warnings or hints, but also simply for quotes. Currently it's not obvious to the reader what the severity/importance of each blockquote is. This PR makes that more obvious by using "warning callouts" for warnings and "info callouts" for hints.
Warnings, for example, now look like this:
<details>
<summary>Show screenshot</summary>
</details>
Take a look at the docs.page preview for my branch: https://docs.page/DoctorJohn/react-native-google-ads~clarify-severity
:fire:
> docs: clarify severity of callouts

- docs/displaying-ads-hook.mdx
- docs/displaying-ads.mdx
- docs/index.mdx
When this package was still part of rnfirebase, gatsby was used for the docs which enabled the generation of reference api docs. This is not an option with docs.page which we currently use for docs. This left us with a bunch of broken links to non-existing api reference docs. This PR updates all these links to point to the source code instead.
- Fixes #591
- Docs preview: https://docs.page/DoctorJohn/react-native-google-ads~fix-broken-links
> docs: fix broken reference links

- android/build.gradle
- ios_config.sh
This PR adjust the expo managed workflow detection to no longer yield false-positives for bare RN projects using expo modules.
- Fixes #614
- Successfully ran jest tests
- Successfully built and ran the bare test app
- Successfully built and ran EAS builds for android and ios
> fix: expo managed project detection

- android/build.gradle
- ios_config.sh
This PR fixes builds of projects that don't have app.json file at all.
This is done by fixing two bugs:
1. The bailout conditions added in #616 turned out to be tautoligical. They try to detect managed expo projects during build time by checking the existance of `android` and `ios` folders. These folders will always exist during build time rendering the checks useless. As a result bare react native projects without a valid app.json no longer fail at build time. Note that correctly configured projects are not affected by this bug at all (that's why my testing did not reveal this bug).
2. Builds of any android app without app.json files currently fail because of a missing check for the availability of the parsed contents of that file.
Note that this PR fully removes the bailout conditions …
> fix: building without an app.json file

- docs/european-user-consent.mdx
- docs/index.mdx
This PR clarifies that `app.config.js` and `app.config.ts` files are still supported (just like `app.json` files).
~This PR complements the `app.json` config examples with `app.config.js` and `app.config.ts` examples.~
~I was hoping we would not have to do this since it's somewhar cluttering the docs, but I tried to compensate that by using docs.page accordion components. Also tried using nested tabs, but they don't appear to be supported (i.e. they don't render correctly).~
- #620
Hope this helps with issues like this, where some people got the impression that `app.config.*s` support was dropped
- Validate the changes via the [docs preview](https://docs.page/DoctorJohn/react-native-google-ads~add-app-config-examples)
> docs: clarify app.config.*s files are supported

- src/validateAdRequestOptions.ts
> fix: set default internal request agent

- tsconfig.json
- type-test.ts
This PR fixes that our compile time type tests were never evaluated. Furthermore, it also updates the tests to include all types that have been added since their last update.
- Fixes #615 
- Made sure `yarn tsc:compile` now passes
- Checked that all types exported from `src/index.ts` are covered
> test: fix outdated and unused type tests

- package.json
- tsconfig.json
- tsconfig.test.json
As reported in https://github.com/invertase/react-native-google-mobile-ads/issues/631#issuecomment-2397953899, PR #619 broke the generation of TS types shipped with the package.
The reason for this is the inclusion of the `type-test.ts` file in the `include` array in the `tsconfig.json` file. This was done so that the `tsc:compile` script used by the lint CI workflow would try to compile that file and report any issues with it. This was inspired by how it's done in the [react-native-firebase repo's tsconfig.json](https://github.com/invertase/react-native-firebase/blob/9c940857a3759f85fad2f8d995b83f7c08058d6b/tsconfig.json#L2).
However, unlike react-native-fiebase we ship those compiled files and the inclusion of the `type-test.ts` file is messing with the structure of the output files. …
> fix: type tests were messing with type generation

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java
- ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
- type-test.ts
Add a function to get purpose legitimate interests.
This library exposes a function to get purpose consents; however it lacks a function to get the status of purpose legitimate interests. Knowing which legitimate interests were selected (or rather deselected) is essential. This information helps determine what type of ads will be served to the user (personalized, non-personalized or limited ads), if any.
More about it here:
https://developers.google.com/admob/ios/privacy/ad-serving-modes
N/A
---
Think …
> feat: get purpose legitimate interests

- android/src/main/java/io/invertase/googlemobileads/OnNativeEvent.kt
Disable native event coalescing by setting canCoalesce to false. This library uses a single event definition for multiple events. If they happen almost at the same time, some events would otherwise get ignored.
N/A
android: Fix issue where some native events may not be triggered
---
> fix(android): disable coalescing of native events

- docs/european-user-consent.mdx
- src/AdsConsent.ts
- src/types/AdsConsent.interface.ts
While checking the official ios docs for changes I noticed that Google uses a helper method in their examples which I think can benefit this library too. Making it less cumbersome to show a consent form when necessary.
So you don't first have to call `requestInfoUpdate` and then `loadAndShowConsentFormIfRequired `.
But just `gatherConsent`.
See: https://github.com/googleads/googleads-mobile-ios-examples/blob/043de5a21d5b529ded1fb845f9f8082d130113f8/Objective-C/admob/BannerExample/BannerExample/GoogleMobileAdsConsentManager.m#L45
And: https://developers.google.com/admob/ios/privacy#request-ads
> feat: gather consent method to make user consent easier

- android/src/main/AndroidManifest.xml
This PR resolves a conflict in AndroidManifest.xml for the property android.adservices.AD_SERVICES_CONFIG. The issue occurs when both react-native-google-mobile-ads (via play-services-ads-lite) and @react-native-firebase/analytics (via play-services-measurement-api) declare the same property, causing a build failure.
By adding tools:replace="android:resource" to the <property> element in the react-native-google-mobile-ads manifest, this library takes precedence, resolving the conflict and allowing the project to build successfully.
Fixes #657 
Added tools:replace="android:resource" to <property> in AndroidManifest.xml of react-native-google-mobile-ads.
This ensures compatibility when used with libraries like @react-native-firebase/analytics.
- I read the [Contributor …
> fix: resolve AndroidManifest conflict for AD_SERVICES_CONFIG

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsModule.kt
Required for Unity Ads to function in mediation, as far as I can see shouldn't effect anything else
Use currentActivity to initialise ads if available
- [ x] Yes
- [ x] `Android`
- [ x] No
🔥
> fix(android): use currentActivity in initialize if !null, aids use of mediation adapters

- __tests__/consent.test.ts
- package.json
- src/AdsConsent.ts
- src/specs/modules/NativeConsentModule.ts
UMP SDK release notes:
To support testing with regulated US states, added the following options to [UMPDebugGeography](https://developers.google.com/admob/ios/privacy/api/reference/Enums/UMPDebugGeography):
UMPDebugGeographyRegulatedUSState
UMPDebugGeographyOther
Deprecated UMPDebugGeographyNotEEA. Use UMPDebugGeographyOther instead.
> feat: update mobile ads sdk, ump sdk and add new geography options

- ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.mm
- ios/RNGoogleMobileAds/RNGoogleMobileAdsInterstitialModule.mm
- ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm
- ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedInterstitialModule.mm
- ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedModule.mm
requiresMainQueueSetup was accidentally removed by #662, which now triggers warnings that it requires main queue setup.
This PR brings them back.
> fix: warning requiresMainQueueSetup

- ios/RNGoogleMobileAds/RNGoogleMobileAdsNativeView.mm
Somehow I implemented the logic for registering the native asset view in iOS (old architecture) incorrectly.
This caused the native assets to not respond to clicks, and issues showed up in the Native Ad Validator.
Fixes #685, fixes #694
---
> fix(ios): register asset view properly in old arch

- .github/workflows/create_test_patches.yml
Uses `@react-native-community/cli init` in create test patch workflow as `react-native init` is removed.
---
> ci: use @react-native-community/cli init

- android/src/oldarch/com/facebook/react/viewmanagers/RNGoogleMobileAdsMediaViewManagerDelegate.java
- android/src/oldarch/com/facebook/react/viewmanagers/RNGoogleMobileAdsNativeViewManagerDelegate.java
React Native 0.77 removes `BaseViewManagerInterface`, this PR follows a similar approach applied [here](https://github.com/AppAndFlow/react-native-safe-area-context/pull/566) to add support for RN77 and old architecture.
According to [this](https://github.com/facebook/react-native/pull/46809), the change should be backwards compatible with older versions of RN.
Fixes #701.
Updated old architecture code to support React Native 0.77 on Android. 
This should be covered by the CI, although requires the example …
> fix(android): fix for android build on RN77

- package.json
Version 12.3.0 of the SDK for iOS was released two weeks ago and contains no breaking changes, only the following fix: "Resolved a crash related to SKOverlay dismissal in Unity apps". Should be a simple non-breaking SDK bump.
- appears to be working with patch-package in my app
- let's see what CI has to say
---
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) …
> feat(deps): update mobile ads sdk - ios 12.3.0

- plugin/__tests__/__snapshots__/plugin.test.ts.snap
- plugin/__tests__/plugin.test.ts
- plugin/src/index.ts
This PR makes the expo config plugin idempotent (i.e., `npx expo prebuild` can now be run idempotent without duplicate values ending up in any manifests).
- Fixes #747 
- Closes #750 
- I added new snapshot tests and carefully reviewed them
- While the issue prompting this PR was focused on Android, I also added a test making sure the plugin behaves as expected regarding Info.plist modifications
:fire:
> fix(expo): make the config plugin idempotent

- android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
- docs/displaying-ads.mdx
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.m
- ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerView.mm
- src/ads/BaseAd.tsx
- src/types/BannerAdProps.ts
Add onAdImpression and onAdClicked event listeners for Banner Ads
Fixes #794
- Add onAdImpression and onAdClicked event listeners for Banner Ads
:fire:
> feat(banner): Add onAdImpression and onAdClicked event listeners
