invertase/react-native-google-mobile-ads

RNGoogleAds.podspec
Setting $RNGoogleAdsSDKVersion and/or $RNGoogleAdsAsStaticFramework is currently not working.
=> fix: missing dollar sings

README.md
=> docs: display documentation as list

jest.setup.ts
=> fix: jest task fails

ios/RNGoogleAds/RNGoogleAdsBannerViewManager.m
- Banner methods were renamed in v8.
- adViewWillLeaveApplication was removed.
=> feat: replace banner v7 methods with v8 methods

.eslintignore, .eslintrc.js, .github/PULL_REQUEST_TEMPLATE.md, example/e2e/init.js, lib/ads/InterstitialAd.js, lib/ads/RewardedAd.js, lib/common/Base64.js, lib/common/path.js, lib/googleMobileAds.js, lib/index.js
Presumably, this gets rid of require cycles in the code, and removes a bit of unused code.
Fixes #34 
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
---
Think `react-native-admob` is great? Please consider supporting the project with any of the below:
=> refactor: eliminates require cycles, and some unused code

ios/RNGoogleAds/RNGoogleAdsInterstitialModule.m
=> fix(ios): adUnitId is nil on interstitial load error

android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsCommon.java, docs/displaying-ads.mdx, ios/RNGoogleAds/RNGoogleAdsCommon.m
Some errors remain "unknown" and therefore in some cases it's hard to understand what goes wrong in case of errors.
=> feat: extended error logging

android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
See discussion https://github.com/facebook/react-native/issues/32649#issuecomment-990968256
- I read the [Contributor Guide](https://github.com/invertase/react-native-google-ads/blob/main/CONTRIBUTING.md)
- [x ] Yes
- [x ] `Android`
- [x ] No
=> fix: Block descendant focus requests Resolves #55

android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsAppOpenModule.java, android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsEvent.java, android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsPackage.java, docs/displaying-ads.mdx, docs/index.mdx, example/App.tsx, ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.h, ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.h, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m, src/MobileAds.ts, src/TestIds.ts, src/ads/AppOpenAd.ts, src/ads/InterstitialAd.ts, src/ads/MobileAd.ts, src/ads/RewardedAd.ts, src/index.ts, src/types/GoogleMobileAdsNativeModule.ts, src/types/RequestOptions.ts
Add App Open Ads support.
https://developers.google.com/admob/ios/app-open
https://developers.google.com/admob/android/app-open
=> feat: app open ads

docs.json, docs/common-reasons-for-ads-not-showing.mdx
Should guide all new users with ads not showing troubles.
=> docs: add guide for ads not showing

RNGoogleMobileAds.podspec, android/build.gradle, package.json
=> fix: android version and app keys

docs/european-user-consent.mdx
A few additions to the docs I promised in #96 ticket discussion.
Fixes #96 
---
=> docs: minor additions to the ads consent docs

RNGoogleMobileAdsExample/App.tsx, android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsCommon.java, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m, src/BannerAdSize.ts
=> feat: add inline adaptive banners support

ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.h, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsInterstitialModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedInterstitialModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedModule.m
Should fix: #133
Needs thorough testing.
Code borrowed from: https://github.com/expo/expo/blob/d84b7ae9c09e1377f415004167c70ea51b888d56/packages/expo-modules-core/ios/EXUtilities.m#L40
=> fix(ios): already presenting another view controller

android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsFullScreenAdModule.kt
Apparently on load of full screen ads, some devices don't have the methods we expect from the admob SDK, and an InvocationTargetException is thrown, bubbles all the way up and crashes the app.
It seems reasonable to catch it locally there, but there may be other issues during load and there really is no reason to *ever* crash with a loading issue, so with this PR:
- we now wrap the entire load sequence in a try/catch, 
- we log warn (because it represents a serious failure, but we can recover) the exception
- we transmit an error event to the JS layer
This will prevent any crashes (such as from InvocationTargetExceptions) during load, with logging and error reporting
Fixes #214 
commit message is conventional, semantic-release should work
- I read the [Contributor …
=> fix(android): robustly handle full-screen load exceptions

docs/index.mdx
Expo users frequently struggle to configure this library correctly and to build their app so that the changes take effect. This PR updates the docs with extra instructions for expo users to hopefully prevent this in the future.
- Related to #238 and various others
Proofread my additions. They match the advice we gave users in the many related issues.
:fire:
---
- 👉 …
=> docs(expo): add expo app.json setup instructions

package.json
=> fix(deps): android sdk 21.3.0 / ios sdk 9.12.0

.github/ISSUE_TEMPLATE/Bug_report.yml
Some user complained that the issue form requried them to check the Typescript checkbox, even though they didn't use Typescript. I fix that by making that checkbox optional. While I was at it I validated the whole yaml file using a schema (https://json.schemastore.org/github-issue-forms.json). Turns out the render attributes were wrong too 🫠 and the `assignees` top level key should be removed if not used. So I fixes those issues as well :)
I pushed those changes to the main branch of my fork so they can be …
=> chore: issue template fixes

docs/displaying-ads-hook.mdx
=> docs(hooks): add info about `isClicked` value for hooks documentation

RNGoogleMobileAds.podspec, ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsAppOpenModule.swift, ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.h, ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerComponent.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsBannerViewManager.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.h, ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsFullScreenAd.swift, ios/RNGoogleMobileAds/RNGoogleMobileAdsFullScreenContentDelegate.swift, ios/RNGoogleMobileAds/RNGoogleMobileAdsInterstitialModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsInterstitialModule.swift, ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedInterstitialModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedInterstitialModule.swift, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedModule.m, ios/RNGoogleMobileAds/RNGoogleMobileAdsRewardedModule.swift
Adds a bunch of pre-processor directives all around the codebase to ensure the library does not break Mac Catalyst builds, and all its APIs just do nothing on that platform.
Fixes #354 
I've tested it with a real project of mine (still can't make the example app in the repo work for me):
- It works as before when I am building my project with these changes.
- It does not break Mac Catalyst builds anymore, and my project works fine on my machine, with no additional code changes it just does not show any ads …
=> feat(catalyst): support building on catalyst, though ads will not work

RNGoogleMobileAdsExample/package.json, RNGoogleMobileAdsExample/yarn.lock, ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm
Fixes error while trying to build the app on iOS.
=> fix(ios): incompatible integer to pointer conversion

CONTRIBUTING.md, README.md
While reading the contributor guidelines again, I noticed some leftovers from when this code was extracted from rnfirebase. Also the master branch has been renamed to main and one of the readme links had a misleading title.
I previewed the rendered markdown locally
---
=> docs: update contributor guidelines

src/ads/BaseAd.tsx
=> fix: banner ad not showing when requestoptions absent

package.json, yarn.lock
This PR removes unneeded dev dependencies. Looks like they're leftovers from rnfirebase.
I checked where these were used in rnfirebase and whether we still need them, which we don't.
CI should be happy.
---
=> chore: remove unneeded dev dependencies

android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
=> fix(android): crash when activity context not available

docs/index.mdx
This package works flawlessly with Expo, but it appears some Expo users have trouble with the installation instructions.
This PR clearifies the Expo installation instructions and adds a warning about Expo Go not being supported.
We could go further and recommend expo dev-clients and mention that eas can be run locally to convice people to migrate away from Expo Go. But at this point we would just be copying half of the Expo docs over here, which feels way out of scope.
- Resolves #451
- Resolves #437
Waiting …
=> docs(expo): clearify build instructions

docs/common-reasons-for-ads-not-showing.mdx
Added private DNS provider to the reasons for ads not showing document, as some of us were having unexplained issues for ads not showing on both emulators and physical devices, caused by private DNS providers.
Fixes #455 
Fixes #473 
---
=> docs(ads-not-showing): added private dns reason for ads not showing

docs/ad-inspector.mdx
- Adding instructions to debug menu
=> docs(menu): adding instructions on how to open debug-menu

android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java, ios/RNGoogleMobileAds/RNGoogleMobileAdsConsentModule.m, src/AdsConsent.ts, src/types/AdsConsent.interface.ts
Add a method to expose the IABTCF_gdprApplies value.
So you can determine if GDPR rules applies in the current context.
=> feat: add method to check if gdpr applies

android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java
=> fix(android): commands mapped incorrectly

docs/index.mdx
The current link does not redirect correctly to the correct section
🔥
---
=> docs: anchor link for redirecting to Banner

src/ads/BaseAd.tsx, src/validateAdRequestOptions.ts
Default agent was never added to banner and in cases where no options where specified.
Fixes #658
=> fix: missing default requestagent

docs/displaying-ads.mdx
As their has been advice before in multiple issues but this keeps on getting reported, I found it time to add an example myself to the docs.
Fixes #648
=> docs(iOS): prevent unreachable close button

README.md, android/src/main/java/io/invertase/googlemobileads/ReactNativeAppModule.java, android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsModule.kt, ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm, ios/RNGoogleMobileAds/common/RNAppModule.m, src/common/constants.ts, src/specs/modules/NativeGoogleMobileAdsModule.ts
Port the precision constants to the new arch.
=> feat(ios): precision constants on new arch

README.md
Add a description of which formats there are available / when to use them.
=> docs(readme): available ad formats

RNGoogleMobileAdsExample/ios/Podfile, RNGoogleMobileAdsExample/ios/Podfile.lock, RNGoogleMobileAdsExample/ios/RNGoogleMobileAdsExample.xcodeproj/project.pbxproj
Disables ccache in example app, as it is not working well for now.
---
=> build: disable ccache in example app

package.json
=> build(deps): update mobile ads sdk - ios 12.2.0 android 24.1.0

package.json
=> feat(deps): update mobile ads sdk - ios 12.4.0 android 24.3.0

docs/index.mdx
update index.md to include all possible types of ads in docs
update index.md to include all possible types of ads in docs
---
=> docs: update index.md to include all possible types of ads in docs
